# Generated by Django 4.2.4 on 2023-08-24 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('slot', models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 22, 17, 498931, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
            ],
        ),
    ]
