# Generated by Django 4.2.4 on 2023-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slot',
            field=models.DateTimeField(),
        ),
    ]
